### ISSUE TITLE
socket_import_stream() and TCP_NODELAY

### ISSUE THREAD

**Issue by alex-nevidomy** [nrk/predis#266] opened 2015-07-17 18:22 UTC
Hi all !
I checked this code from PhpiredisStreamConnection.php (set $parameters->tcp_nodelay to 1):
$socket = $socket ?: socket_import_stream($resource);
socket_set_option($socket, SOL_TCP, TCP_NODELAY, (int) $parameters->tcp_nodelay);

...code executed OK, but it has no any effect for me (Linux cs20605 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u2 x86_64, PHP 5.4.41-0+deb7u1 (cli)), Nagle's algorithm works anyway (checked by tcpdump).

Any idea?

**Comment by nrk** [comment] 2015-07-23 08:54
What kind of effect are you expecting that is not delivered by setting the `TCP_NODELAY` flag?

**Comment by alex-nevidomy** [comment] 2015-07-23 14:33
> What kind of effect are you expecting that is not delivered by setting the TCP_NODELAY flag?

When I send small packets of data it will be sent not immediatelly (as expected after set TCP_NODELAY), but still will wait some time (because of Nagle's algorithm), so looks like TCP_NODELAY is not set really.

**Comment by nrk** [comment] 2015-07-24 10:30
@alex-nevidomy I did an `strace` of the PHP CLI process and the `TCP_NODELAY` socket option is successfully set on the underlying socket resource (`setsockopt()` returns `0` thus no error) when specifying `tcp_nodelay=1` in the connection parameters, as you can see in the last line here:

```
connect(3, {sa_family=AF_INET, sin_port=htons(6379), sin_addr=inet_addr("172.22.109.80")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=3, revents=POLLOUT}])
getsockopt(3, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
fcntl64(3, F_SETFL, O_RDWR)             = 0
getsockopt(3, SOL_SOCKET, 0x27 /* SO_??? */, [2], [4]) = 0
fcntl64(3, F_GETFL)                     = 0x2 (flags O_RDWR)
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
```

The function `socket_import_stream()` makes it possible to access the underlying "raw" socket resource wrapped by a PHP stream so that you can set flags otherwise inaccessible when using the stream interface.

**Comment by alex-nevidomy** [comment] 2015-07-24 15:06
Did you check the data sending after you set TCP_NODELAY option? Data were sent immediately?
Could you please show tcpdump of your test?

**Comment by nrk** [comment] 2015-08-16 08:09
Well the fact that the the low-level `setsockopt()` does not return an error code means that the operating system set the `TCP_NODELAY` on the resource but from that point whatever happens (e.g. the network stack is forced to act accordingly) is unfortunately beyond our reach. Anyway I tried a few times to reproduce latency by issuing commands that generate small packets but had no luck, even without setting the `TCP_NODELAY` (I'm developing locally on multiple virtual machines so it wouldn't surprise me if the network stack acted in a different matter), so all I can say for now is that it did indeed work last time I performed more extensive tests while implementing this feature.

You could try using `Predis\Connection\PhpiredisSocketConnection` which relies directly on socket resources (requires `ext-socket` and `ext-phpiredis`) instead of PHP streams and see if you notice any different behaviour.

I'm closing this issue for now because I'm pretty sure it's not directly attributable to Predis but feel free to add more details if needed.

**Closed by nrk** 2015-08-16 08:09 UTC
