### ISSUE TITLE
Sentinel support broken in simple environments

### ISSUE THREAD

**Issue by tback** [nrk/predis#337] opened 2016-05-24 16:20 UTC
Hi @nrk.
Great work on #131!

Sentinel support is broken for simplistic environments though. 
In a setup with a single sentinel and a single redis-server without slaves it will err with `Expected slave but got master` on `client->get('foo')`. 
To reproduce the error clone https://github.com/tback/predis_sentinel_error and run `docker-compose up`. #

**Comment by tback** [comment] 2016-05-24 16:52
A little information on top (it's also in the repo):
This was tested with predis 7b3f6e1db556a8309eb4ef372b55667fc97419d2 on php 5.5.35 against redis 2.8 on debian (inside docker).

**Comment by nrk** [comment] 2016-05-25 09:05
@tback hmm I already have a guess about why that happens, but I'll have a look later today or tomorrow. BTW thanks for the great way to make the error easily reproducible :+1:

**Comment by nrk** [comment] 2016-05-25 14:29
@tback I pushed a fix so it should be fine now, I even added a test to avoid regressions in the future but it would be great if you could double check that everything is working as expected.

The problem was due to a wrong expectation being made when asserting the role of the node picked to perform a read-only operation: normally Predis checks that `ROLE` returns `slave` when connecting to a slave to send a read-only command but in this specific case, when we only have the master server with no slaves, the client is allowed to use the master server for read-only commands too so it's perfectly fine to expect that `ROLE` will return `master`. Before the fix Predis erroneously checked that the response to `ROLE` was that of a slave getting the one of a master instead, thus ending up in a loop of retry attempts interrupted only when `$retryLimit` (set to `20` by default) was reached.

Thanks!

**Comment by nrk** [comment] 2016-06-01 13:57
I did some further testing and everything looks indeed fine after the fix so I'm closing this issue. By the way I'm planning to release Predis v1.1.0 early tomorrow (CEST).

**Closed by nrk** 2016-06-01 13:57 UTC
Labels: bug, redis-sentinel
