### ISSUE TITLE
ConnectionFactoryOption do not recognize Predis\Configuration\Options

### ISSUE THREAD

**Issue by thiagof** [nrk/predis#487] opened 2018-02-14 15:46 UTC
There is an environment problem apparently triggering this error

```Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Predis\Configuration\ConnectionFactoryOption::getDefault() must be an instance of Predis\Configuration\OptionsInterface, instance of Predis\Configuration\Options given, called in /www/sites/laravel/vendor/predis/predis/src/Configuration/Options.php on line 64 in /www/sites/laravel/vendor/predis/predis/src/Configuration/ConnectionFactoryOption.php:50```

PHP 7.0.8-3+deb.sury.org~trusty+1 (cli) ( NTS )

**Comment by nrk** [comment] 2018-03-06 15:13
There's Laravel in the mix and I don't know anything about Laravel nor know what it does to initialize instances of Predis (which is most likely the cause of the exception) so I'm closing this issue. If you have more details or even better a small snippet that only uses Predis to reproduce the issue, then feel free to reopen it so that I have at least some actual hints.

**Closed by nrk** 2018-03-06 15:13 UTC
